version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: task_management_db_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

<<<<<<< HEAD
=======
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_management_api
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}"
      NODE_ENV: development
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

>>>>>>> 2058b16264571558f9262dcda0c627b5e99995cf
volumes:
  postgres_data:
